version: '2'

volumes:
    influxdb-data:
    dashboard-data:
services:
  influxdb:
    container_name: influxdb
    image: influxdb@sha256:73f876e0c3bd02900f829d4884f53fdfffd7098dd572406ba549eed955bf821f
    restart: always
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - 'influxdb-data:/data'
    ports:
      - "8086:8086"
  mqtt:
    build: ./mqtt
    restart: always
    ports:
      - "1883"
  telegraf:
    build: ./telegraf
    privileged: true
    restart: always
    depends_on:
      - mqtt
      - influxdb
  dashboard:
    build: ./dashboard
    restart: always
    expose:
      - '80'
    volumes:
      - 'dashboard-data:/data'
    depends_on:
      - influxdb
  temperature:
    build: ./temperature
    privileged: true
    restart: always   
    depends_on:
     - mqtt
  windvane:
    build: ./windvane
    privileged: true
    restart: always
    depends_on:
     - influxdb
     - dashboard
  raingauge:
    build: ./raingauge
    privileged: true
    restart: always   
    depends_on:
     - mqtt
  anemometer:
    build: ./anemometer
    privileged: true
    restart: always   
    depends_on:
     - mqtt
  humidity:
    build: ./humidity
    privileged: true
    restart: always
    depends_on:
     - mqtt
  api:
    container_name: api
    build: ./api
    restart: always
    expose:
      - "4567"
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
    - dashboard
