version: '2'

volumes:
    influxdb-data:
    dashboard-data:
services:
  influxdb:
    container_name: influxdb
    image: arm64v8/influxdb:1.8.6
    restart: always
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - 'influxdb-data:/var/lib/influxdb'
    ports:
      - "8086:8086"
  mqtt:
    build: ./mqtt
    restart: always
    ports:
      - "1883"
  telegraf:
    build: ./telegraf
    privileged: true
    restart: always
    depends_on:
      - mqtt
      - influxdb
  dashboard:
    build: ./dashboard
    restart: always
    ports:
      - '80'
    volumes:
      - 'dashboard-data:/data'
    depends_on:
      - influxdb
  temperature:
    build: ./temperature
    privileged: true
    restart: always
    depends_on:
     - mqtt
  windvane:
    build: ./windvane
    privileged: true
    restart: always
    depends_on:
     - mqtt
  raingauge:
    build: ./raingauge
    privileged: true
    restart: always
    depends_on:
     - mqtt
  anemometer:
    build: ./anemometer
    privileged: true
    restart: always
    depends_on:
     - mqtt
  humidity:
    build: ./humidity
    privileged: true
    restart: always
    depends_on:
     - mqtt
  solar:
    image: hferentschik/solar-edge:0.0.1
    restart: always
    depends_on:
     - mqtt
  api:
    container_name: api
    build: ./api
    restart: always
    expose:
      - "4567"
