# frozen_string_literal: true

source 'https://rubygems.org'

gem 'httparty'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'tzinfo'

group :test, :development do
  gem 'rack-test'
  gem 'rake'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'rubocop'
end
